"""initial migration

Revision ID: 08dcd0693a53
Revises: e11de84ba6b5
Create Date: 2026-04-01 00:59:01.395100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08dcd0693a53'
down_revision: Union[str, Sequence[str], None] = 'e11de84ba6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_history_user'), table_name='history')
    op.create_index('idx_history_user_anime', 'history', ['user_id', 'anime_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_user_anime', table_name='history')
    op.create_index(op.f('idx_history_user'), 'history', ['user_id'], unique=False)
    # ### end Alembic commands ###
